### ISSUE TITLE
audio clicking

### ISSUE THREAD

**Issue by diggly** [libretro/gambatte-libretro#12]
It seems there is some nasty audio clicking in a lot of games I've tried (particularly noticable when bringing up the pause menu in Link's Awakening DX)

Would a declicking feature (like VBA-M has) be possible?

**Comment by twinaphex** [comment]
The libretro version is now as up-to-date as upstream. 

Could you try again in case you still care about this issue?

**Comment by SigmaVirus** [comment]
This issue is very much still valid as of today 2016.

I'm using a nightly build of the gambatte-libretro core dated 2016-02-27 and the audio clicks when you enter the pause menu of Link's Awakening.

However, this also occurs on other emulators such as BGB 1.5.2 which in terms of accuracy is on par with gambatte.

Whether or not this behavior is expected on real hardware I don't know.

**Comment by DanielJGC** [comment]
Is there anything further on this issue? I'm playing the Oracle of X Zelda games and they exhibit quite a bit of popping during dialogue boxes and scrolling through menus, and also random pops during gameplay. In trying different emulators to try and get rid of this problem I noticed that VBA has a "declicking" option for audio. It seems to be a know problem with no solution that I can see.

**Comment by KreativeKrise** [comment]
I've got the same problems :pensive:

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#39

**Comment by OptimalJew** [comment]
I'd love to hear a recording of menu interactions on the Oracle games taken from a CGB to see if it's indeed an issue on original hardware. Strangely, the issue is not present on BGB which is supposedly accurate.
