### ISSUE TITLE
Buildbot failures

### ISSUE THREAD

**Issue by RokkumanX** [libretro/gambatte-libretro#149]
Hi!

For the last 9 months the buildbot have failed to build the core, is there something that have happened?

Will it ever work again?

Thanks in advance!

**Comment by hizzlekizzle** [comment]
It only seems to be failing on MSVC2010. Is that what you mean?

The error there seems to be:
`LINK : fatal error LNK1146: no argument specified with option '/out:'`
which looks to be related to:
https://github.com/libretro/gambatte-libretro/blob/master/Makefile.libretro#L622
I don't know anything about compiling with MSVC, so I don't know how it would affect other MSVC flavors if that were changed to /out instead of -out. Perhaps @twinaphex knows.

**Comment by RokkumanX** [comment]
@hizzlekizzle 

Thanks for taking your time reply to my issue, I appreciate it!

I think I was a bit unclear of what buildbot I meant, it's this one:
https://ci.appveyor.com/project/bparker06/gambatte-libretro/history

As you can see pretty much every build since August is red and have failed.

I have been able to built the core with MSYS2 myself so it's not that big of a deal but something with the provided buildbot is wrong.

**Comment by hizzlekizzle** [comment]
ahhh, okay, yeah that one's probably not going to succeed anymore. We have our own buildbot that distributes via RetroArch's online updater, and we may do some more stuff soon-ish using Travis, but the appveyor stuff was setup by a guy who is no longer with the project, so it's not likely to be updated.

**Comment by RokkumanX** [comment]
Thanks for explaining this to me, it's a shame that he left but at least now I know why the builds are failing all the time.

Have a nice day @hizzlekizzle !
