### ISSUE TITLE
Save states not working on Zelda Links awakening. 

### ISSUE THREAD

**Issue by Zelex** [libretro/gambatte-libretro#21]
Reboots the game instead of loading the save state. Occurs on retro_serialize or retro_unserialize.

**Comment by SigmaVirus** [comment]
I don't mean to be a necro here or anything but this issue can be closed since long, I can save state and reload just fine.

I have two versions of the game, Zelda no Densetsu - Yume o Miru Shima (Japan) and Legend of Zelda, The - Link's Awakening DX (Europe) which don't show any symptoms of failing when it comes to save states.

Likely, https://github.com/libretro/gambatte-libretro/commit/12c1ff30688cdf7abeee57a4ebddcd84d3697e06 solved this problem.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#40

**Comment by twinaphex** [comment]
According to @meepingsnesroms , this can be closed now.
