### ISSUE TITLE
Gambatte 3ds sound crackling

### ISSUE THREAD

**Issue by fraf** [libretro/gambatte-libretro#92]
Hi debuggers,

I submit  a  new issue on sound issue with gambatte. I tested on gbc games like Zelda awakening DX. At start, the sound crackling problem arrives. This problem hasard been detected since few month ago. It concerns as well   the lastest retroarch version as older version. But ne carreful, this issue IS not systematic. Sometimes it works but when sound crackling occurs, it persists. Even if i reboot thé 3ds.
Here my test rig:
N3ds + luma3ds 8.1.1 with boot9strap.
Retroarch 1.6.9 release (latest)

**Comment by fraf** [comment]
The louder the sound level the more crakling

**Comment by meepingsnesroms** [comment]
Dump your DSP payload: [DSP1 Dumper](https://gbatemp.net/threads/dsp1-a-new-dsp-dumper-cia-for-better-stability.469461/) 
Then switch the audio driver to dsp instead of csnd.(this happened in mame2000 at first for me too)
Reload the emulator.

If there are still issues post what did or dident change.

**Comment by fraf** [comment]
Same problem !
But it is no so embarrasing bug. Indeed, until +0...+2, sound volume, the sound is good. But louder sound start to be crackling, at loudest it is clearly deformed sound !.
This bug is minor in fact because all is working at "normal sound volume".

Thx.
